//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class taccount
    {
        public long ACCOUNTID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMAILADDRESS { get; set; }
        public string ISENABLED { get; set; }
        public string POSTTOSLACK { get; set; }
        public string SLACKBOTCHANNEL { get; set; }
        public string PASSWORD { get; set; }
        public string ROLE { get; set; }
    }
}
