//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkey
    {
        public long KEYID { get; set; }
        public long ACCOUNTID { get; set; }
        public string EXCHANGE { get; set; }
        public string APIKEY { get; set; }
        public string APISECRET { get; set; }
        public string PASSPHRASE { get; set; }
    }
}
