//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmarket
    {
        public int MarketID { get; set; }
        public string EXCHANGE { get; set; }
        public string EXCHANGEMARKET { get; set; }
        public string STMARKET { get; set; }
        public string BASECURRENCY { get; set; }
        public string MARKETCURRENCY { get; set; }
    }
}
