//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmarkettick
    {
        public long tTickID { get; set; }
        public string Exchange { get; set; }
        public string Market { get; set; }
        public decimal BaseVolume { get; set; }
        public decimal TickClose { get; set; }
        public decimal TickHigh { get; set; }
        public decimal TickLow { get; set; }
        public decimal TickOpen { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public decimal Volume { get; set; }
        public string TickType { get; set; }
    }
}
