//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmastertrade
    {
        public int MASTERID { get; set; }
        public long ACCOUNTID { get; set; }
        public string EXCHANGE { get; set; }
        public string TRADETYPE { get; set; }
        public string TRADINGPAIR { get; set; }
        public string BUYPRICE { get; set; }
        public string BUYQUANTITY { get; set; }
        public Nullable<decimal> BUYTOTAL { get; set; }
        public string SELLPRICE { get; set; }
        public string SELLQUANTITY { get; set; }
        public string FIRSTACTION { get; set; }
        public Nullable<System.DateTime> LASTRUN { get; set; }
        public System.DateTime NEXTRUN { get; set; }
        public long RUNFREQUENCY { get; set; }
        public long RUNLIMIT { get; set; }
        public long RUNCOUNT { get; set; }
        public string ACTIVE { get; set; }
        public string SELLTOTAL { get; set; }
    }
}
