//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tworker
    {
        public int WorkerID { get; set; }
        public string WorkerName { get; set; }
        public string WorkerHost { get; set; }
        public string WorkerLogLevel { get; set; }
        public string WorkerActive { get; set; }
        public Nullable<System.DateTime> WorkerLiveDate { get; set; }
        public Nullable<System.DateTime> WorkerLastCheckIn { get; set; }
        public string WorkerExchange { get; set; }
    }
}
