//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tworkerassignment
    {
        public int ASSIGNMENTID { get; set; }
        public string WORKERID { get; set; }
        public string EXCHANGE { get; set; }
        public string MARKET { get; set; }
        public string ACCOUNTID { get; set; }
        public string ASSIGNMENTACTIVE { get; set; }
    }
}
